### ISSUE TITLE
Traffic Light Tests

### ISSUE THREAD

**Issue by ghost** [CompassSoftware/TraffSim#17]
Test for #3 

Would be dependent on data from other classes, **possibly** not writeable for just me.
i.e. i would need to make sure lights at perpendicular lanes are never both green, which would require information from the lanes object given to the light by the controller.

**Comment by ghost** [comment]
Aside from this, test accessors and mutators, etc

**Comment by ghost** [comment]
Test made, just need to review the makefile in the Calculator assignment and make sure i know how to compile and launch it

**Comment by ghost** [comment]
Testfile complete, compiling, and working(?)

when the tests are run, 0 tests are failed and 0 tests are passed, and 2 containers are successful.

**Comment by brownje3** [comment]
I don't think you're running the test. Just compiling.

**Comment by ghost** [comment]
After some minor fixes and replacing `assert`s with `assertEquals` or `assertTrue`, still running into the same issue. No one can see an immediate error in the makefile or the test file, but the class itself appears to work fine

**Comment by ghost** [comment]
Tests working, now just implementing a few more to test a few different components
