### ISSUE TITLE
Traffic light with discrete states

### ISSUE THREAD

**Issue by ghost** [CompassSoftware/TraffSim#3]
Make a class for the traffic light that allows for the creation of a traffic light object with discrete states for the different lights that can be imported to other classes and changed.

**Comment by ghost** [comment]
Subtask of #1 

Implementation time: **1 - 1.5 hours**

**Comment by ghost** [comment]
Suggested implementation: a TrafficLight class containing an enum field of type Light.
This Light should contain the constants **GREEN**, **YELLOW**, and **RED** for this stage of the project.

**Comment by ghost** [comment]
Since controller is handling the decision making, TrafficLight should be made with the sole intention of sending controller current information so it can give accurate commands, and following the commands controller gives.

**Comment by ghost** [comment]
JUnit tests required before writing code.

Implementation time: **2 hours**
Time includes making tests and learning how to actually make JUnit tests, might take longer

Since the controller will drive the program in the future, the JUnit tests should test TrafficLight by providing phony sensor info

**Comment by fenwickjb** [comment]
@FlygonJin okay for TrafficLight to have an enum representing current state. But in reality, this physical entity has 3 constituent BULB entities. 

So changing from yellow to red is MORE than just updating a field from YELLOW to RED. It is actually also telling a yellow bulb to turn off and a red bulb to turn on.

**Comment by ghost** [comment]
Class made and currently ready for merging with master, despite troubles with test files

**Comment by ghost** [comment]
Added bulb objects as fields, kept enum as a method of calling from outside the class
Now the TraficLight class automatically sets the light bulbs on or off dependent upon the enum value whenever the setter is called

**Comment by ghost** [comment]
Considering automatically changing light from yellow to red with an attatched print statement whenever
`TrafficLight.setColor(BulbColor.YELLOW)`
is called, because a light never stays at yellow.

**Comment by ghost** [comment]
Finally got class confirmed working with tests

**Comment by callitsishe** [comment]
This class took approximately 3 hours to complete.
