### ISSUE TITLE
Timer class

### ISSUE THREAD

**Issue by ghost** [CompassSoftware/TraffSim#38]
Used to make a MinTimer for each sensor and MaxTimer for the entire intersection.
Estimated Time: **2hr**

After every sensor trigger while the light is green, a MinTimer should begin counting to (10). If its sensor is triggered again while counting, it restarts. Once the timer reaches (10) the lights will cycle.

The MaxTimer counts to (60) and will cycle the lights no matter what once reaching (60)

There will also be timers to make yellow lights wait (5) before turning red, and make red lights wait (5) after perpendicular lanes hit red before changing to green

**Comment by ghost** [comment]
Lane class should be modified to have a timer field.
The maxtimer could either be created by the simulator or, preferably, be a field in the controller

**Comment by ghost** [comment]
Current bottleneck to testing logic in `Simulator`, along with #50

**Comment by putneyrj** [comment]
Took **3hrs**

**Comment by fenwickjb** [comment]
I'm confused. I see this issue is named "Timer class" but then it says "Lane should have a timer" so it supposed to be in Lane? And then a comment about Simulator? And then the code changes that came from this issue are comments to Lane?
Ugh... Confusing...
@callitsishe and @fenwickjb worked on a true Timer class on Wed Jul 24. Can't find that code anywhere. So, I'm posting it on a new branch called real-timer (the old Timer branch didn't have a Timer class?)

**Comment by fenwickjb** [comment]
Oh, the TimerTest is not a JUnit style test though. It's a standalone application. But you should be able to convert it fairly easily.

**Comment by fenwickjb** [comment]
Duh?! Now I see the Timer class. :( And I can see that you are using a global Clock type of a solution. Which was not Hayden and my original thought process. 
But I'm still going to put that code on the real-timer branch in case anyone wants it. It can be used in either of two ways: polling the timer to see if it's done or telling the timer to do a "callback" when it expires. The key is that the Timer class sets up its own thread to do it's timing separate from the client code that is using the timer. You should look at it. It's actually pretty cool code. ;-)

**Comment by callitsishe** [comment]
This class took approximately 3 hours to complete.
