### ISSUE TITLE
Car Class

### ISSUE THREAD

**Issue by brownje3** [CompassSoftware/TraffSim#4]
Make a car class. It interacts with the Lane (location or direction) and Sensor (onSensor and to tell sensor where it is). The car will stop at the light and tell the sensor it is there. It will get the direction from the Lane. It will go depending on when the controller sends a signal. This will take about 1.5 hours to make and test.

**Comment by brownje3** [comment]
#1

**Comment by brownje3** [comment]
Completed Car, but still need to keep things open ended for cooperation with the other classes.

**Comment by callitsishe** [comment]
This class took approximately 1 hour to complete.
