### ISSUE TITLE
Fix UML Documents

### ISSUE THREAD

**Issue by ghost** [CompassSoftware/TraffSim#43]
Update UML documents to reflect current master branch

**Comment by fenwickjb** [comment]
@FlygonJin, where are these UML documents? I can't find them in the master branch.

**Comment by ghost** [comment]
Share Link: 
https://drive.google.com/file/d/1U0YeZdGE0koc1pUH35MT7z78EqhWiPkI/view?usp=sharing
I'll put a link in the readme too
