### ISSUE TITLE
Fixing up to previous sprint

### ISSUE THREAD

**Issue by ghost** [CompassSoftware/TraffSim#74]
Log of progress and problems faces while changing all files to account for last week's scenario.
Estimated Time: 4hrs

**Comment by ghost** [comment]
`run1`, the method made to handle the scenarios being logged here, is running fine until it starts feeding east lane cars through, and an out of bounds index is referenced. Issues like this have been found previously and are usually minor logic errors that are easily overlooked.

Once this section of code is able to send both the cars through and run the simulation's timer up I need to add the following:

**Handle paired lanes**: As north land sends cars, south lane should as well, etc. 
**Change text for empty cars**: Right now an empty car being sent through gives the same feedback as a real car, and this can be confusing.
**Fix `Car.stop`**: basically give it the same treatment `Car.go` was given in class.

**Comment by ghost** [comment]
**Probably Terrible Idea** :- keep a constant number of fake cars in each lane, change the remove and add methods in `CarList` to just replace those spots.

As long as i never have to actually COUNT the cars in a lane this shouldn't be that bad an idea.

**Comment by ghost** [comment]
All errors cleared, simulation exits properly, touching things up to make sure both cars left the intersection properly.

**Comment by ghost** [comment]
Problem with never reaching the real cars. Seems to be linked to the car in the first position being not real

**Comment by ghost** [comment]
Simulation is working, all cars are being sent through, it's just taking far more ticks **(about 100 on the globaltimer)** than it will in the future because the lanes aren't being handled in pairs and the lights aren't cycling early, meaning there are a lot of ticks where nothing changes.

**Comment by ghost** [comment]
Added `begin` target in makefile, just runs a `make compile` followed by a `make run`

**Comment by ghost** [comment]
Changes committed to  [**SimFixSprint2-2**](https://github.com/CompassSoftware/TraffSim/tree/SimFixSprint2-2)

**Comment by ghost** [comment]
The cars are leaving correctly, but I have no logic to make the lanes change faster when a lane is empty

**Comment by ghost** [comment]
Student machine down all day, limited changes made.
Currently the amount of ticks it takes to remove both cars has been brought down but isn't at the expected amount. I'mm need to make sure both lanes are filtering at once in a pair and that empty spots are always removed when there is a car present in the lane.

think about restructuring the inner loop to change the active lane once per globaltick

**Comment by ghost** [comment]
Idk how to move forward; can't work out how to get `sendCar` to cycle the lights early. Removing the `minTimer` requirement for the lights to cycle early didn't help.

**Comment by ghost** [comment]
Additionally, the globaltimer in `run1` is going on for around four times longer than it should

**Comment by ghost** [comment]
Problem in `lanesWithCar`: only adds lanes to the array that have a real car in the first position. I've commented out this condition.

**Comment by ghost** [comment]
I currently can't tell if the program is running as planned or not: the `clock` timestamps are disjointed from `globaltimer` in a way i can't diagnose.

**Comment by howardsl1** [comment]
**Actual Timestamp** 24 hours
