### ISSUE TITLE
Lanes

### ISSUE THREAD

**Issue by callitsishe** [CompassSoftware/TraffSim#9]
My group and I have met as a team to discuss which class each of us would be working on and how each class functions with the rest of the program. For instance, I am working on the lanes class solely, and I have determined that this class will only extend from the control panel (master class). logically speaking (uml mindset), my class will take a true/false input from control panel and this will pass through a series of if/while checks to determine what lanes are on/off. This should be simple considering the cars are only moving in parallel directions currently (no turning).

**Comment by callitsishe** [comment]
TLDR: I will write a program that will show the direction that each lane is moving to. 

Methods Used: I will only extend from control panel class.

James Input: James needs this method to determine where the cars are going for his car class.

Time Frame: It will problem only take me by the end of tomorrow to program this.

**Comment by fenwickjb** [comment]
I'm confused what "where the cars are going" means. If you are the East-bound lane then the cars are going east. Basically, the lane just knows if it has cars on its sensor(s). Maybe not even cars! Whatever object might trigger a sensor (bike, motorcycle, fallen tree, heavy snow, ???). The control panel would probably be the object that knows that a particular Lane object is the east-bound lane.

**Comment by howardsl1** [comment]
Working on Lane class to work along with sensor class and traffic light class. **TIMESTAMP** 4 hours.
